-- 코드를 작성해주세요
SELECT
    YEAR(DIFFERENTIATION_DATE) YEAR,
    N.SIZE_MAX - E.SIZE_OF_COLONY AS YEAR_DEV,
    E.ID
FROM ECOLI_DATA E JOIN
    (
        SELECT YEAR(DIFFERENTIATION_DATE) YEAR, MAX(SIZE_OF_COLONY) SIZE_MAX
        FROM ECOLI_DATA
        GROUP BY YEAR(DIFFERENTIATION_DATE)
    ) N ON (YEAR(E.DIFFERENTIATION_DATE) = N.YEAR)
ORDER BY YEAR, YEAR_DEV


