SELECT
    I.ITEM_ID,
    I.ITEM_NAME,
    I.RARITY
FROM
    ITEM_INFO I
WHERE
    NOT EXISTS
    (SELECT
        T.PARENT_ITEM_ID
    FROM
        ITEM_TREE T
    WHERE
        I.ITEM_ID = T.PARENT_ITEM_ID)
ORDER BY
    I.ITEM_ID DESC